#  Metirc
- 모델 성능 평가지표
- 실제값과 모델에 의해 예측된 값을 비교하여 모델의 성능을 측정
- 모델 평가 목적
    - 최적의 모델을 찾기 위해

- 회귀 문제 성능측정
    - 실제값과 예측값의 차이를 측정

# 회귀 문제 성능측정

## 당뇨병 진행 예측
- 당뇨병 진행도를 예측하는 데이터셋

In [4]:
!pip install scikit-learn

     ---------------------------------------- 8.2/8.2 MB 35.0 MB/s eta 0:00:00
     --------------------------------------- 14.8/14.8 MB 50.3 MB/s eta 0:00:00
     --------------------------------------- 39.9/39.9 MB 27.3 MB/s eta 0:00:00
     ---------------------------------------- 298.0/298.0 kB ? eta 0:00:00


In [5]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
diabetes.data, diabetes.target

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [6]:
data=diabetes.data
target=diabetes.target

In [7]:
target.shape

(442,)

In [8]:
print(target.min())
print(target.max())

25.0
346.0


## 학습셋과 검증셋 분리

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid=train_test_split(data,target,test_size=0.2)
#sklearn.model_selection.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
#xtrain,xvalid,ytrain,yvalid 순서입니다.

## Linear Regression 모델을 이용한 학습 및 예측

In [11]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
y_valid_predict=model.predict(x_valid)

In [14]:
y_valid_predict

array([235.36654465, 111.44604079,  46.18907786, 266.25848578,
       123.71262787, 201.70016257, 145.71787655, 132.65689837,
       242.07494132, 194.8787345 , 177.48090607, 259.4067687 ,
       158.06251996, 131.69071088, 130.43457901,  76.20224144,
       226.44444681, 105.29326073, 155.15360965,  90.71478392,
        57.89201686, 126.53496411,  58.67267421,  66.92193769,
       148.12774579, 151.89781084, 152.4935812 , 237.46969516,
       268.31839795,  81.17834811,  96.08901605, 103.39440898,
       187.68924446, 127.07755187, 179.76149454, 205.38433299,
       194.35271092, 157.4316772 , 182.9481774 , 141.4396194 ,
        92.48682628, 180.34614226,  85.41188426, 103.4583333 ,
       192.91563351, 176.87844901, 190.17035896,  98.72567903,
        43.20932591, 169.05100251, 203.73603527, 147.53887669,
        69.32900521, 199.66387861, 164.20141181, 254.72357256,
       189.22605214, 127.5987153 ,  75.8931169 , 145.00050077,
       161.29114568, 132.7135107 , 118.6870092 , 157.39

## 회귀 평가 지표


### MSE(Mean Squared Error)
$$
MSE = \frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}
$$
- 실제값과 예측값의 차이를 제곱해서 평균화
- 이상치에 민감
- 직관적이지 못하다.
- 손실함수로 주로 사용한다.

In [15]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_valid,y_valid_predict)
print(mse)

3716.867098010312


### RMSE(Root Mean Squared Error)
$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$
- MSE에 루트
- 이상치 민감


In [17]:

# 방법1
import numpy as np
np.sqrt(mse)

# 방법2
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
rmse=mean_squared_error(y_valid,y_valid_predict,squared=False)
print(rmse)

60.96611434239771


### MAE(Mean Absolute Error)
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$
- 실제값과 예측값의 차이를 절대값으로 변환해서 평균화
- 직관적이다.

In [18]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_valid,y_valid_predict)
mae

49.99894763792065

### MAPE (Mean Absolute Percentage Error)
$$
MAPE = \frac{100}{n}{\sum_{i=1}^{n}\frac{|y_i-\hat{y}_i|}{y_i}}
$$
- 실제값에 대한 절대오차 비율의 평균을 퍼센트로 표현

In [19]:

# 방법1
def mape(true,pred):
   return np.mean(np.abs((true - pred) / true))
mape(y_valid,y_valid_predict)

# 방법2
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_valid, y_valid_predict)

0.4883131513947471

### SMAPE (Symmetric Mean Absolute Percentage Error)
$$
SMAPE = \frac{100}{n}{\sum_{i=1}^{n}\frac{|y_i-\hat{y_i}|}{{|y_i|}+|\hat{y_i}|}}
$$
- 기존 mape의 단점을 보완한것
- MAPE와 다른점은 각 실제값과 예측값을 절대값으로 변경후 핪으로 나눈다.
- MAPE와 다르게 실제값에 0이 존재해도 계산이 가능하다.
- 실제값보다 예측값이 크거나 작을수도있다.
- 예측값이 실제값보다 작을때, 분모가 작아지기 때문에 오차가 커지게 된다. (과소추정에 대한 패널티가 줄수가 있다.)


In [ ]:
def smape(true,pred):
   error =  np.abs(true - pred) / (np.abs(true) + np.abs(pred))
   return np.mean(error) # 퍼센트로 나타낼꺼면 100 곱해주면됨
smape(y_valid,y_valid_predict)

0.15271360402048711

### 결정계수 R2 
- 결정계수는 실제 관측값의 분산대비 예측값의 분산을 계산하여 데이터 예측의 정확도 성능을 측정하는 지표 
- 0~1까지 수로 나타내어지며 1에 가까울수록 100%의 설명력을 가진 모델이라고 평가를 하게된다.
- R^2 =1 : 현재 가지고 있는 X변수로 Y를 100% 설명. 즉, 모든 관측치가 회귀직선에 있다.
- R^2 = 0 : 현재 가지고 있는 X변수는 Y 설명(예측)에 전혀 도움이 되지 않는다
- 사용하고 있는 X변수의 품질
- 변수가 많아지면 많아질수록 무조건 값이 올라감


$$
R^2 = \frac{SSR}{SST} =\frac{오차^2}{편차^2} =  1- \frac{SSE}{SST}
$$

- SST (Sum of Squared Total): 관측치 - 예측평균값
$$
{\sum_{i=1}^{n}(y_i-\bar{y})^2}
$$
- SSE (Sum of Squared Error): 관측값 - 예측값, 즉 잔차제곱합 RSS와 같은 의미이다.
$$
{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}
$$
- SSR (Sum of Squares due to Regression): 예측값 - 예측평균값
$$
{\sum_{i=1}^{n}(\hat{y_i}-\bar{y})^2}
$$

In [21]:
from sklearn.metrics import r2_score
r2_score(y_valid, y_valid_predict)

0.35017023542175296

## adjusted R square
![crash](https://i.stack.imgur.com/fLrDw.png)

- adjusted r square 
- p=독립변수의 개수 
- p가 분모에 위치하면서 p가 증가함에 따라 분자에 있는 rsquare의 증가영향을 어느 정도 상쇄해줌.
- adj rsquare은 따라서 rsquare 보다 작음