# 텐서(Tensor)

In [ ]:
import torch
import numpy as np

In [ ]:
print(" torch: {}".format(torch.__version__))
print(" Use GPU? {}".format(torch.cuda.is_available()))

 torch: 1.13.1+cu116
 Use GPU? True


```python
torch.Tensor와 torch.tensor의 차이

- "torch.Tensor"
    - 클래스 (Class)
    - int 입력시 float로 변환
    - torch 데이터 입력시 입력 받은 데이터의 메모리 공간을 사용
    - list, numpy 데이터 입력 시 입력 받은 데이터를 복사하여
      새롭게 torch.Tensor를 만든 후 사용
- "torch.tensor"
    - 함수 (Function)
    - int 입력시 int 그대로 입력
    - 입력 받은 데이터를 새로운 메모리 공간으로 복사 후 사용

아래의 코드를 작성해놨는데 보면서 명확하게 이해해볼게요.

** 다 알고 있는 것 같지만, 잊지말아야할 Tip
클래스 (Class)는 앞글자가 대문자로 시작하고
함수 (Function)은 앞글자가 소문자로 시작해요!
이 규칙은 PyTorch 전반에 걸쳐서 잘 적용되어 있어요.
```

In [ ]:
# torch.Tensor - [torch.Tensor 입력]
print("torch.Tensor는 torch 데이터 입력시 메모리 공간을 그대로 사용합니다!")
print("기존 Tensor의 값을 수정하면 새롭게 만들어진 Tensor의 값도 수정됩니다!")
print("-" * 50)
original_data = torch.Tensor([1])
new_data = torch.Tensor(original_data)
print(f"original : {original_data} new : {new_data}")
 
# original data를 수정하자
original_data[0] = 2
print(f"original : {original_data} new : {new_data}")

torch.Tensor는 torch 데이터 입력시 메모리 공간을 그대로 사용합니다!
기존 Tensor의 값을 수정하면 새롭게 만들어진 Tensor의 값도 수정됩니다!
--------------------------------------------------
original : tensor([1.]) new : tensor([1.])
original : tensor([2.]) new : tensor([2.])


In [ ]:
# torch.Tensor - [list, numpy 입력]
print("torch.Tensor는 list, numpy 데이터 입력시 데이터를 복사하여 사용합니다!")
print("기존 데이터 값을 수정해도 새롭게 만들어진 Tensor에게 영향을 주지 않죠!")
print("-" * 50)
original_data = [1]
new_data = torch.Tensor(original_data)
print(f"original : {original_data} new : {new_data}")

# original data를 수정하자
original_data[0] = 2
print(f"original : {original_data} new : {new_data}")

torch.Tensor는 list, numpy 데이터 입력시 데이터를 복사하여 사용합니다!
기존 데이터 값을 수정해도 새롭게 만들어진 Tensor에게 영향을 주지 않죠!
--------------------------------------------------
original : [1] new : tensor([1.])
original : [2] new : tensor([1.])


In [ ]:
# torch.tensor - [torch.Tensor 입력]
print("torch.tensor는 어떤 데이터가 입력되든 데이터를 복사하여 사용합니다!")
print("기존 데이터 값을 수정해도 새롭게 만들어진 Tensor에게 영향을 주지 않죠!")
print("-" * 50)
original_data = torch.tensor([1])
new_data = torch.tensor(original_data)
print(f"original : {original_data} new : {new_data}")

# data를 수정하자
original_data[0] = 2
print(f"original : {original_data} new : {new_data}")

torch.tensor는 어떤 데이터가 입력되든 데이터를 복사하여 사용합니다!
기존 데이터 값을 수정해도 새롭게 만들어진 Tensor에게 영향을 주지 않죠!
--------------------------------------------------
original : tensor([1]) new : tensor([1])
original : tensor([2]) new : tensor([1])


<ipython-input-12-67ddb4fd2d22>:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  new_data = torch.tensor(original_data)


## Quiz

`torch.add`, `torch.sub`, `torch.mul`, `torch.div`를 통해 변수를 선언하고 ((4*2)-(1+2)) - 5 를 계산해주세요!

In [ ]:
A = torch.Tensor([4])
B = torch.Tensor([2])
C = torch.Tensor([1])
D = torch.Tensor([2])
E = torch.Tensor([5])

# 1줄에 torch함수 하나씩만 사용하세요!
out1 = None
out2 = None
out3 = None

output = None

print("result = {}".format(output))

result = tensor([0.])


# 텐서 행렬

In [ ]:
# list 로부터 2x3 텐서 생성
x_list = [[1, 2, 3], [4, 5, 6]]
x = torch.Tensor(x_list)
print(x)

# numpy array 로부터 2x3 텐서 생성
x_numpy = np.array([[1, 2, 3], [4, 5, 6]])
x = torch.Tensor(x_numpy) # float형으로 출력
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


다시 원래 자료형태로 복귀

In [ ]:
# .tolist()
x_back2list = x.tolist() # 같은 level(위치)에 있는 데이터끼리 묶어준다.
print(type(x_back2list))

# .numpy()
x_back2numpy = x.numpy()
print(type(x_back2numpy))

<class 'list'>
<class 'numpy.ndarray'>


## Data to Tensor

In [ ]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

### ndArray to Tensor

In [ ]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex) # 배열에서 tensor로 바꾸기. torch.Tensor와 동일한 기능이지만, float출력이 아닌 int로 바꿈
tensor_array

tensor([[ 3,  5],
        [10,  5]])

In [ ]:
data = [[3, 5],[10, 5]]
nd_array_ex = np.array(data)
tensor_array1 = torch.tensor(nd_array_ex)
tensor_array1

tensor([[ 3,  5],
        [10,  5]])

In [ ]:
print(tensor_array.dtype)
print(tensor_array1.dtype)

torch.int64
torch.int64


GPU를 사용하려면 `device` 정보를 텐서에 `string` 타입으로 전달해줘야한다. 
* "cuda": GPU 사용
* "cpu": CPU 사용

In [ ]:
# 기본 device 정보
print("텐서 x 의 device:", x.device)

device = 'cuda'
# GPU 사용
x = x.to(device)
print("device 정보 전달 후, 텐서 x 의 device:", x.device)

device = 'cpu'
# CPU 사용
x = x.to(device)
print("device 정보 전달 후, 텐서 x 의 device:", x.device)

텐서 x 의 device: cpu
device 정보 전달 후, 텐서 x 의 device: cuda:0
device 정보 전달 후, 텐서 x 의 device: cpu


### 랜덤 텐서 생성하기
* `torch.manual_seed`: 동일한 결과를 만들 도록 seed를 고정한다.
* `torch.rand`: [0, 1) 사이의 랜덤 텐서 생성
* `torch.randn`: 평균=0, 표준편차=1 인 정규분포로부터 랜덤 텐서 생성
* `torch.randint`: [최저값, 최대값) 사이에서 랜덤 정수 텐서 생성

In [ ]:
torch.manual_seed(777)
# 랜덤 숫자로 구성된 크기가 2x3 인 텐서 생성
# 0과 1사이의 랜덤한 숫자
print("torch.rand\n-------------")
x = torch.rand(2, 3)
print(x)
print()

# 평균=0, 표준편차=1 정규분포에서 생성
print("torch.randn\n-------------")
x = torch.randn(2, 3)
print(x)
print()

# 0과 8 사이의 정수형 랜덤한 숫자
print("torch.randint\n-------------")
x = torch.randint(low=0, high=8, size=(2, 3))
print(x)
print()

torch.rand
-------------
tensor([[0.0819, 0.4911, 0.4033],
        [0.3859, 0.8813, 0.8811]])

torch.randn
-------------
tensor([[ 0.3688, -1.3005, -2.0292],
        [ 0.1283,  0.6558, -0.6138]])

torch.randint
-------------
tensor([[6, 0, 3],
        [1, 2, 4]])



### 기존의 텐서크기와 같은 0 혹은 1 텐서 생성

* `torch.zeros_like`: 입력 텐서와 같은 크기, 타입, 디바이스로 0으로 채워진 텐서를 생성한다.
* `torch.ones_like`: 입력 텐서와 같은 크기, 타입, 디바이스로 1로 채워진 텐서를 생성한다.

In [ ]:
# GPU를 사용하고 크기가 x 와 같은 0으로 채워진 텐서 생성
x_zeros = torch.zeros_like(x.cuda())
print(x_zeros.device)
print(x_zeros)

cuda:0
tensor([[0, 0, 0],
        [0, 0, 0]], device='cuda:0')


## Quiz

- 0부터 9사이의 랜덤 정수 3 * 4크기의 행렬을 만들고, 다른 행렬은 디바이스로 1로 채워진 동일한 크기의 텐서를 생성한 후 두 행렬을 더해서 결과를 출력해주세요.

In [ ]:
A = None
B = None

output =  None
print(output)