#torch.nn 문서 읽기
``` python
설명에 그래프를 만들기 위한 "basic building block"이라고 쓰여져 있습니다!

저희가 다양한 함수들을 잘 활용하면
여기서 말하는 "basic building block"을 만들 수 있겠지만 시간이 걸리니까
PyTorch에서 미리 만들어두고 이를 "torch.nn"으로 묶어 쉽게 사용하게 만들었어요! 

여기서 제공해주는 블럭들을 잘 이용하면 그래프라는 딥러닝 모델을 만들 수 있을 것 같아요!

매우 중요해보이지만 내용이 정말 많네요!
이 많은 내용을 다 볼 수는 없으니까 간단하게 훑어보겠습니다!
```

- [torch.nn 문서 - PyTorch 공식 문서](https://pytorch.org/docs/stable/nn.html)

## torch.nn `Linear Layers`

``` python
가볍게 읽기만 하려고 했는데 그래도 한 두개는 직접 예제를 따라치면 좋을 것 같아요!
딥러닝을 공부하면, y = WX + b 라는 공식을 자주 볼거예요!
이 linear transformation을 구현해놓은 "nn.Linear"가 속해잇는
"Linear Layers" 항목을 잠깐만 같이 살펴보겠습니다!
```

- [torch.nn Linear Layers - PyTorch 공식 문서](https://pytorch.org/docs/stable/nn.html#linear-layers)

### nn.Linear


``` python
pytorch로 딥러닝 설계를 한다면, 이 "nn.Linear"는 정말 많이 보게 될거예요!
```

- [torch.nn.Linear - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear)

**힌트**
- PyTorch에는 tensor 크기(or 모양)를 반환하는 함수가 있어요! 영어로 크기가 무엇일까요?

In [ ]:
import torch
from torch import nn

X = torch.Tensor([[1, 2],
                  [3, 4]])

# TODO : tensor X의 크기는 (2, 2)입니다
#        nn.Linear를 사용하여서 (2, 5)로 크기를 바꾸고 이 크기를 출력하세요!

linear = nn.Linear(2,5)
output = linear(X) # 저장된 객체에 X를 호출 (함수에 X를 적용)
output.size()

torch.Size([2, 5])

### nn.Identity
이 layer도 유용하게 사용됩니다. 다만 딥러닝을 막 배우는 단계에서 이 layer를 사용할 일은 거의 없기 때문에 사용처를 아실 필요는 없습니다. 다만 궁금해하실 분들을 위해 링크를 남겨놓습니다.

``` python
"nn.Identity"는 입력과 출력이 동일하게 나오는데 도대체 왜 만들어놓은 걸까요?
그래도.. 한번 사용해봐요!
```

- [torch.nn.Identity - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Identity.html#torch.nn.Identity)

**유용한 자료**
- [What is the use of nn.Identity? - PyTorch Forum](https://discuss.pytorch.org/t/what-is-the-use-of-nn-identity/51781)
- [What is the idea behind using nn.Identity for residual learning? - Stack Overflow](https://stackoverflow.com/questions/64229717/what-is-the-idea-behind-using-nn-identity-for-residual-learning)

In [ ]:
import torch
from torch import nn

X = torch.Tensor([[1, 2],
                  [3, 4]])

# TODO : nn.Identity를 생성해 X를 입력시킨 후 나온 출력값이 X와 동일한지 확인해보세요!
identity = nn.Identity()
output = identity(X)
output

tensor([[1., 2.],
        [3., 4.]])

# Custom 모델 제작을 위한 nn.Module 클래스

```
PyTorch 라이브러리가 제공해주는 다양한 기능들과 nn.Module를 활용하여 모델 제작 및 분석을 진행해볼 것입니다!
```

PyTorch가 제공해주는 기능들을 조합하여서 모델을 만들 차례입니다. 모델을 만들기 위해서 기능들을 단순히 나열해놓기만 한다면 지저분하겠죠? 그래서 PyTorch는 이런 일련의 기능들을 한 곳에 모아 하나의 모델로 추상화할 수 있게끔 클래스를 제공합니다.

```
nn.Module
```
- [torch.nn.Module - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html)

`nn.Module` 클래스는 여러 기능들을 한 곳에 모아놓는 상자 역할을 합니다.<br>
`nn.Module`이라는 상자는 다른 `nn.Module` 상자를 포함할 수도 있습니다!<br>
어떻게 사용햐느냐에 따라 `nn.Module` 상자는 다른 의미를 가집니다.

- `nn.Module`이라는 상자에 `기능`들을 가득 모아놓은 경우 `basic building block`
- `nn.Module`이라는 상자에 `basic building block`인 `nn.Module`들을 가득 모아놓은 경우 `딥러닝 모델`
- `nn.Module`이라는 상자에 `딥러닝 모델`인 `nn.Module`들을 가득 모아놓은 경우 `더욱 큰 딥러닝 모델`

`nn.Module`은 빈 상자일 뿐 이를 어떻게 사용할지는 온전히 설계자의 몫입니다!<br>
`기능`과 `basic building block`과 `딥러닝 모델`을 혼재해서 마구잡이로 담을 수도 있고<br>
`기능`은 `기능`끼리 `block`은 `block`끼리 계층적으로 담을 수도 있습니다!

우리는 여기서 `nn.Module`를 이용해 모델을 제작해보고 제작한 모델이 어떻게 구성되어있는지 분석해볼 것입니다!<br>
추가적으로 custom 모델 제작에 유용할 수 있는 `nn.Module`의 기능들도 살펴볼 것입니다!

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)

- Documentation에서 nn.Module을 검색해서 찾으세요!
- nn.Module 문서의 설명을 읽어보세요!
    - ![](https://github.com/IllgamhoDuck/PyTorch/blob/main/document_image/nn.Module.png?raw=true)
- nn.Module 내부의 method들의 이름과 설명을 가볍게 훑어보세요!

## nn.Module 모델 제작

"nn.Module"를 이용해서 더하기 연산을 하는 모델을 만들어봅시다!

In [ ]:
import torch
from torch import nn

# TODO : Add 모델을 완성하세요!
class Add(nn.Module):
    def __init__(self):
        # TODO : init 과정에서 반드시 들어가야 하는 super 관련 코드가 있습니다
        # 자식 클래스(Student)가 상속받는 부모 클래스(Human)를 자식 클래스(Student)에 불러오겠다
        # super().__init__() 의 역할 즉, 자식 클래스에도 부모 클래스의 인스턴스 속성과 동일한 속성이 생성
        super().__init__()
    def forward(self, x1, x2):
        # TODO : torch.add 함수를 사용해서 더하기 연산을 해주세요!
        output = torch.add(x1,x2)

        return output


# 아래 코드는 수정하실 필요가 없습니다!
x1 = torch.tensor([1])
x2 = torch.tensor([2])

add = Add()
output = add(x1, x2)

output #3

tensor([3])

``` python
super를 통해서 init을 하는 것은 왜 그런걸까요?

아래 링크의 글을 읽으니까 의문이 좀 풀리는 것 같아요! 
```

**유용한 자료**
- [Why is the super constructor necessary in PyTorch custom modules? - Stack Overflow](https://stackoverflow.com/questions/63058355/why-is-the-super-constructor-necessary-in-pytorch-custom-modules)

### Container

``` python
저희가 원하는 모듈(Module)을 만들었습니다!

이렇게 만든 모듈(Module)들을 묶어서 사용하고 싶은데 어떻게 하는걸까요?
파이썬의 리스트에 모듈들을 보관하면 되는걸까요?

Documentation을 열심히 찾아보니까 관련된 함수들이
"torch.nn"의 Container 항목에 포함되어있네요!
```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)
- [Containers  - PyTorch 공식 문서](https://pytorch.org/docs/stable/nn.html#containers)

##### torch.nn.Sequential

``` python
모듈(Module)들을 하나로 묶어 순차적으로 실행시키고 싶을때 torch.nn.Sequential를 사용한다고 합니다!
```

- [torch.nn.Sequential - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html#torch.nn.Sequential)

In [ ]:
import torch
from torch import nn

# TODO : 다음의 모듈(Module)을 읽고 이해해보세요!
class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

# TODO : 위에 모듈(Module)과 nn.Sequential를 이용해서
#        입력값 x가 주어지면 다음의 연산을 처리하는 모델을 만들어보세요!
#        y = x + 3 + 2 + 5
calculator = nn.Sequential(Add(3),
                           Add(2),
                           Add(5),)


# 아래 코드는 수정하실 필요가 없습니다!
x = torch.tensor([1])

output = calculator(x)

output # 11

tensor([11])

#### torch.nn.ModuleList

``` python
torch.nn.Sequential은 묶어놓은 모듈들을 차례대로 수행하기 때문에 실행 순서가 정해져있는 기능들을 하나로 묶어두기 좋아보입니다!

하지만 파이썬의 list처럼 모아두기만 하고 그때그때 원하는 것만
인덱싱(indexing)을 통해 쓰고 싶으면 torch.nn.ModuleList을 쓰면 되지 않을까요?
```

- [torch.nn.ModuleList - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html#torch.nn.ModuleList)

In [ ]:
import torch
from torch import nn

# TODO : 다음의 모듈(Module)을 읽고 이해해보세요!
class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value


# TODO : Calculator 모델을 완성하세요!
class Calculator(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_list = nn.ModuleList([Add(2), Add(3), Add(5)])

    def forward(self, x):
        # TODO : self.add_list에 담긴 모듈들을 이용하여서
        #        y = ((x + 3) + 2) + 5 의 연산을 구현하세요!
        x = self.add_list[1](x) # Add 객체이므로 value 를 저장하기 위한 입력 x를 받아야겠지?
        x = self.add_list[0](x)
        x = self.add_list[2](x)
     
        
        return x


# 아래 코드는 수정하실 필요가 없습니다!
x = torch.tensor([1])

calculator = Calculator()
output = calculator(x)

output # 11

tensor([11])

####  torch.nn.ModuleDict

``` python
torch.nn.ModuleLists 정말 편리하네요!!
하지만 만약 리스트에 담긴 모듈의 크기가 정말 커진다면 나중에는 인덱싱(indexing)으로 원하는 모듈을 찾기가 정말 힘들어질 것 같아요!

파이썬의 dict처럼 특정 모듈을 key값을 이용해 보관해놓는다면 나중에 원하는 모듈을 가져올때 훨씬 수월하지 않을까요?
마침 PyTorch에 torch.nn.ModuleDict이 있네요! 같이 써봐요!
```

- [torch.nn.ModuleDict - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.ModuleDict.html#torch.nn.ModuleDict)

In [ ]:
import torch
from torch import nn

# TODO : 다음의 모듈(Module)을 읽고 이해해보세요!
class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value


# TODO : Calculator 모델을 완성하세요!
class Calculator(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_dict = nn.ModuleDict({'add2': Add(2),
                                       'add3': Add(3),
                                       'add5': Add(5)})

    def forward(self, x):
        # TODO : self.add_dict에 담긴 모듈들을 이용하여서
        #        y = ((x + 3) + 2) + 5 의 연산을 구현하세요!

        x = self.add_dict['add3'](x) # dict 의 인덱스 호출과 똑같다.
        x = self.add_dict['add2'](x)
        x = self.add_dict['add5'](x)
        
        return x


# 아래 코드는 수정하실 필요가 없습니다!
x = torch.tensor([1])

calculator = Calculator()
output = calculator(x)

output # 11

tensor([11])

### <font color='red'><b>[ 퀴즈 ]</b></font> Python List vs PyTorch ModuleList
``` python
그런데 가만히 생각해보니까 파이썬에도 List가 있는데 왜 굳이 PyTorch에서는 ModuleList를 별도로 만들어두었을까요?

그 이유가 궁금해요!
```

- [torch.nn.ModuleList - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html#torch.nn.ModuleList)

**힌트**
- 아래에 작성된 코드를 실행시키시면 힌트를 얻을 수 있습니다!

In [ ]:
# 아래 코드는 수정하실 필요가 없습니다!
class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value


class PythonList(nn.Module):
    """Python List"""
    def __init__(self):
        super().__init__()

        # Python List
        self.add_list = [Add(2), Add(3), Add(5)]

    def forward(self, x):
        x = self.add_list[1](x)
        x = self.add_list[0](x)
        x = self.add_list[2](x)
        
        return x

class PyTorchList(nn.Module):
    """PyTorch List"""
    def __init__(self):
        super().__init__()

        # Pytorch ModuleList
        self.add_list = nn.ModuleList([Add(2), Add(3), Add(5)])

    def forward(self, x):
        x = self.add_list[1](x)
        x = self.add_list[0](x)
        x = self.add_list[2](x)
        
        return x

In [ ]:
# 아래 코드는 수정하실 필요가 없습니다!
x = torch.tensor([1])

python_list = PythonList()
pytorch_list = PyTorchList()

# 기능 동작은 동일합니다!
print(python_list(x), pytorch_list(x))

tensor([11]) tensor([11])


In [ ]:
# Python List로 모아놓은 모듈들이 감쪽같이 사라졌습니다!
python_list

PythonList()

In [ ]:
# 하지만 PyTorch의 ModuleList로 모아놓은 모듈들은 짠! 하고 나타나네요!
pytorch_list

PyTorchList(
  (add_list): ModuleList(
    (0): Add()
    (1): Add()
    (2): Add()
  )
)

```python
# TODO : 맞고 틀리고가 없는 문제입니다. 문서를 읽고 답을 자유로이 적어주세요


python_list는 클래스 자체(Python_list())를 반환하지만, pytorch_list는 클래스 내의 ModuleList 정보를 함께 반환한다.

기능적으로는 동일하지만 nn.Module 의 submodule 로 등록이 되느냐 마느냐의 차이가 발생하는데, 이 차이로 인해 위의 차이가 발생된다.

더 자세히 말하면, nn Module 내부에서 새로운 변수를 만들 때 '변수 = 값'의 형태로 코드를 적으면 '__setattr__' 의 특수 메서드가 호출된다.


```

### 조건문

``` python
모델을 만들때 PyTorch는 동적 계산 그래프를 사용하기 때문에
if / else 와 같은 조건문을 쉽게 사용할 수 있는 장점이 있습니다!

```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)

**유용한 자료**
- [Can someone explain the use of a dynamic graph? - Reddit](https://www.reddit.com/r/pytorch/comments/8kpsjy/can_someone_explain_the_use_of_a_dynamic_graph/)

In [ ]:
import torch
from torch import nn

# TODO : 다음의 모듈(Module)을 읽고 이해해보세요!
class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

class Sub(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x - self.value


# TODO : Calculator 모델을 완성하세요!
class Calculator(nn.Module):
    def __init__(self, cal_type):
        super().__init__()
        self.cal_type = cal_type
        self.add = Add(3)
        self.sub = Sub(3)

    def forward(self, x):
        # TODO : cal_type에 "add"가 입력되면 더하기 모델 y = x + 3
        #                   "sub"가 입력되면 빼기 모델 y = x - 3
        #                   "add", "sub"가 아닌 다른 문자열이 입력되면 ValueError을 일으키세요!
        #        if/elif/else 조건문을 사용하세요! 
        if self.cal_type == 'add':  # self.cal_type, 초기 생성자의 내용을 참조해야 한다. self 사용에 유의.
          x = self.add(x)
        elif self.cal_type == 'sub':
          x = self.sub(x)
        else:
          raise ValueError


        return x


# 아래 코드는 수정하실 필요가 없습니다!
x = torch.tensor([5])

try:
    calculator = Calculator("none")
    output = calculator(x)

    print("잘못된 문자열 입력에는 에러를 발생시키세요!!")
except ValueError:
    calculator = Calculator("add")
    add_output = calculator(x)

    calculator = Calculator("sub")
    sub_output = calculator(x)
    
    if add_output == 8 and sub_output == 2:
        print("🎉🎉🎉 성공!!! 🎉🎉🎉")
    else:
        print("다시 도전해봐요!")
except:
    print("ValueError를 발생시키세요!!")


🎉🎉🎉 성공!!! 🎉🎉🎉


### Parameter

``` python
linear transformation인 Y = XW + b 에 대해서 생각하고 있었어요!
X는 저희가 torch.Tensor로 만들어서 제공하는데 W, b는 어디서 만들죠?

언뜻 친구한테 들었는데 nn.Module안에 미리 만들어진 tensor들을
보관할 수 있다고 들은 것 같아요! 뭐랬지, 아마 Parameter라고 한 것 같아요!
```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)
- [torch.nn.parameter.Parameter - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.parameter.Parameter.html?highlight=parameter)

**힌트**
- [PyTorch linear.py L81 - L85 - PyTorch 공식 Github](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/linear.py#L81-L85)

In [ ]:
import torch
from torch import nn
from torch.nn.parameter import Parameter


# TODO : Linear 모델을 완성하세요!
class Linear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        # TODO : W, b parameter를 생성하세요! 모두 1로 초기화해주세요!
        self.W = Parameter(torch.ones([out_features, in_features]))
        self.b = Parameter(torch.ones([out_features]))

    def forward(self, x):
        output = torch.addmm(self.b, x, self.W.T)  # WX+ b

        return output


# 아래 코드는 수정하실 필요가 없습니다!
x = torch.Tensor([[1, 2],
                  [3, 4]])

linear = Linear(2, 3)
output = linear(x)


output 
#output == torch.Tensor([[4, 4, 4],
                     # [8, 8, 8]])):

tensor([[4., 4., 4.],
        [8., 8., 8.]], grad_fn=<AddmmBackward0>)

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
import numpy as np
np.dot(np.array([[1,2],[3,4]]),np.ones((2,3)))

array([[3., 3., 3.],
       [7., 7., 7.]])

### Tensor vs Parameter
``` python
생각해보면 W, b도 tensor를 이용하면 되는 것 아닌가요?
왜 굳이 Parameter라는 별개의 클래스를 사용하는 거죠?
```
**힌트**
- 아래에 작성된 코드를 실행시키시면 힌트를 얻을 수 있습니다!

In [ ]:
import torch
from torch import nn
from torch.nn.parameter import Parameter


class Linear_Parameter(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        # torch.nn.parameter.Parameter
        self.W = Parameter(torch.ones((out_features, in_features)))
        self.b = Parameter(torch.ones(out_features))

    def forward(self, x):
        output = torch.addmm(self.b, x, self.W.T)

        return output

class Linear_Tensor(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        # torch.Tensor
        self.W = torch.ones((out_features, in_features))
        self.b = torch.ones(out_features)

    def forward(self, x):
        output = torch.addmm(self.b, x, self.W.T)

        return output


x = torch.Tensor([[1, 2],
                  [3, 4]])

linear_parameter = Linear_Parameter(2, 3)
linear_tensor = Linear_Tensor(2, 3)

output_parameter = linear_parameter(x)
output_tensor = linear_tensor(x)

# 값은 동일하게 계산되는 것을 볼 수 있습니다!
# 하지만 출력을 자세히 보시면, Parameter를 이용해서 W, b를 만들 경우에만
# output tensor에 gradient를 계산하는 함수인 grad_fn가 생성됩니다
print(output_parameter)
print(output_tensor)

tensor([[4., 4., 4.],
        [8., 8., 8.]], grad_fn=<AddmmBackward0>)
tensor([[4., 4., 4.],
        [8., 8., 8.]])


In [ ]:
# Parameter로 만든 W, b는 저장할 tensor로 지정되어있습니다
linear_parameter.state_dict()

OrderedDict([('W', tensor([[1., 1.],
                      [1., 1.],
                      [1., 1.]])), ('b', tensor([1., 1., 1.]))])

In [ ]:
# torch.Tensor로 만든 W, b는 저장되지 않습니다
linear_tensor.state_dict()

OrderedDict()

```python
# TODO : 맞고 틀리고가 없는 문제입니다. 문서를 읽고 답을 자유로이 적어주세요

그냥 하위항목으로 기록되어 호출이 되느냐 안 되느냐의 문제다. 
tensor 은 메서드고 Parameter 은  클래스 객체다. 
tensor 은 그냥 값이고, parameter은 변화가 가능한, 훈련이 가능한 weight다.

Parameter로 파라미터들을 생성해야만,

output tensor에 역전파에서 사용할 gradient를 계산하는 grad_fn이 생성된다
클래스의 .state_dict()로 접근하여 파라미터 정보를 OrderedDict 형태로 획득할 수 있다.



```

###  Buffer

``` python
Custom 모델을 만들때 대부분 torch.nn에 구현된 layer들을 가져가다 사용하기 때문에 Parameter를 직접 다뤄볼 일은 매우 드물어요!

저희가 직접 새로운 layer를 작성할게 아니라면 Parameter를 사용할 일이 거의 없습니다!

하지만 Parameter를 사용할줄 아는 것은 중요하다면서 칭찬해줬어요!
추가적으로 buffer라는 것도 있다면서 가르켜주었죠!

일반적인 Tensor는 Parameter와 다르게 gradient를 계산하지 않아
값도 업데이트 되지 않고, 모델을 저장할 때 무시되잖아요?

하지만 Parameter로 지정하지 않아서 값이 업데이트 되지 않는다 해도
저장하고싶은 tensor가 있을 수도 있잖아요?

그럴때는 buffer에 tensor를 등록해주면 되요!
모델을 저장할때 Parameter뿐만 아니라 buffer로 등록된 tensor들도 같이 저장되요!

정리하면 다음과 같아요!

- "Tensor"
    - ❌ gradient 계산
    - ❌ 값 업데이트
    - ❌ 모델 저장시 값 저장
- "Parameter"
    - ✅ gradient 계산
    - ✅ 값 업데이트
    - ✅ 모델 저장시 값 저장
- "Buffer"
    - ❌ gradient 계산
    - ❌ 값 업데이트
    - ✅ 모델 저장시 값 저장
```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)
- [register_buffer - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=register_buffer#torch.nn.Module.register_buffer)

**유용한 자료**
- [What is the difference between `register_buffer` and `register_parameter` of `nn.Module` - PyTorch Forum](https://discuss.pytorch.org/t/what-is-the-difference-between-register-buffer-and-register-parameter-of-nn-module/32723)

In [ ]:
import torch
from torch import nn
from torch.nn.parameter import Parameter


# TODO : Model 모델을 완성하세요!
class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.parameter = Parameter(torch.Tensor([7]))
        self.tensor = torch.Tensor([7])

        # TODO : torch.Tensor([7])를 buffer이라는 이름으로 buffer에 등록해보세요!
        self.register_buffer('buffer', torch.Tensor([7]), persistent=True)



# 아래 코드는 수정하실 필요가 없습니다!
model = Model()

try:
    buffer = model.get_buffer('buffer')
    if buffer == 7:
        print("🎉🎉🎉 성공!!! 🎉🎉🎉\n")
        print("🎉 이제 buffer에 등록된 tensor는 모델이 저장될 때 같이 저장될거예요! 🎉")
        print(model.state_dict())
    else:
        print("다시 도전해봐요!")
except:
    print("다시 도전해봐요!")


🎉🎉🎉 성공!!! 🎉🎉🎉

🎉 이제 buffer에 등록된 tensor는 모델이 저장될 때 같이 저장될거예요! 🎉
OrderedDict([('parameter', tensor([7.])), ('buffer', tensor([7.]))])


``` python
아 너무 어려워요... 그래서 이걸 어디다 쓰는데요..?
```
``` python
한가지 좋은 예시로 BatchNorm에서 사용되요!
아래 링크를 첨부해놓았으니 더 알고 싶으면 읽어보세요!

이 buffer도 Parameter와 마찬가지로 사용할 일은 드물 것 같아요!
하지만 알아두면 언젠가 요긴하게 쓸 날이 오겠죠?
```


**유용한 자료**
- [torch.nn.BatchNorm1d - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm1d.html?highlight=buffer)
- [PyTorch batchnorm.py L51 - L52 - PyTorch 공식 Github](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py#L51-L52)

## 모델 분석해보기

``` python
이제 직접 모델을 만들어낼 줄 알게 되었습니다!

모델을 만들고 난 후 어떤 module과 parameter를 썼는지
어떻게 알 수 있는 거죠?

느낌상 "nn.Module" Documentation에 그 방법이 나와있을 것 같아요!

제가 전에 작성해놓았던 코드를 가져왔어요! 그때 보셨을 때와 조금 다르죠?
배운 것을 적용해보느라고 조금씩 수정을 해보았어요!
제가 만든 이 모델을 함께 분석해봐요!
```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)
- [torch.nn.Module - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html)

In [ ]:
import torch
from torch import nn
from torch.nn.parameter import Parameter


# 아래 코드는 수정하실 필요가 없습니다!
# 하지만 아래 과제를 진행하기 전에 아래 코드를 보면서 최대한 이해해보세요!

# Function
class Function_A(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name

    def forward(self, x):
        x = x * 2
        return x

class Function_B(nn.Module):
    def __init__(self):
        super().__init__()
        self.W1 = Parameter(torch.Tensor([10]))
        self.W2 = Parameter(torch.Tensor([2]))

    def forward(self, x):
        x = x / self.W1
        x = x / self.W2

        return x

class Function_C(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('duck', torch.Tensor([7]), persistent=True)

    def forward(self, x):
        x = x * self.duck
        
        return x

class Function_D(nn.Module):
    def __init__(self):
        super().__init__()
        self.W1 = Parameter(torch.Tensor([3]))
        self.W2 = Parameter(torch.Tensor([5]))
        self.c = Function_C()

    def forward(self, x):
        x = x + self.W1
        x = self.c(x)
        x = x / self.W2

        return x


# Layer
class Layer_AB(nn.Module):
    def __init__(self):
        super().__init__()

        self.a = Function_A('duck')
        self.b = Function_B()

    def forward(self, x):
        x = self.a(x) / 5
        x = self.b(x)

        return x

class Layer_CD(nn.Module):
    def __init__(self):
        super().__init__()

        self.c = Function_C()
        self.d = Function_D()

    def forward(self, x):
        x = self.c(x)
        x = self.d(x) + 1

        return x


# Model
class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.ab = Layer_AB()
        self.cd = Layer_CD()

    def forward(self, x):
        x = self.ab(x)
        x = self.cd(x)

        return x

x = torch.tensor([7])

model = Model()
model(x)

tensor([6.5720], grad_fn=<AddBackward0>)

### named_children vs named_modules

``` python
제가 만든 모델에서 어떤 module들이 있었는지 기억이 나질 않아요!
그래서 모델 내부의 module들 목록을 보고싶어요!

Documentation을 찾아보니까 children이나 module이라는 이름을 가진
함수가 바로 제가 원하는 기능을 가진 것 같아요!

하지만 이 둘은 무슨 차이일까요?
역시 직접 코드를 통해서 확인해봐야겠어요!
```

- [named_children - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=child#torch.nn.Module.named_children)
- [named_modules - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=named#torch.nn.Module.named_modules)


In [ ]:
for name, module in model.named_modules():
    print(f"[ Name ] : {name}\n[ Module ]\n{module}")
    print("-" * 30)

[ Name ] : 
[ Module ]
Model(
  (ab): Layer_AB(
    (a): Function_A()
    (b): Function_B()
  )
  (cd): Layer_CD(
    (c): Function_C()
    (d): Function_D(
      (c): Function_C()
    )
  )
)
------------------------------
[ Name ] : ab
[ Module ]
Layer_AB(
  (a): Function_A()
  (b): Function_B()
)
------------------------------
[ Name ] : ab.a
[ Module ]
Function_A()
------------------------------
[ Name ] : ab.b
[ Module ]
Function_B()
------------------------------
[ Name ] : cd
[ Module ]
Layer_CD(
  (c): Function_C()
  (d): Function_D(
    (c): Function_C()
  )
)
------------------------------
[ Name ] : cd.c
[ Module ]
Function_C()
------------------------------
[ Name ] : cd.d
[ Module ]
Function_D(
  (c): Function_C()
)
------------------------------
[ Name ] : cd.d.c
[ Module ]
Function_C()
------------------------------


In [ ]:
for name, child in model.named_children():
    print(f"[ Name ] : {name}\n[ Children ]\n{child}")
    print("-" * 30)

[ Name ] : ab
[ Children ]
Layer_AB(
  (a): Function_A()
  (b): Function_B()
)
------------------------------
[ Name ] : cd
[ Children ]
Layer_CD(
  (c): Function_C()
  (d): Function_D(
    (c): Function_C()
  )
)
------------------------------


``` python
아하! 이제 알겠어요!

"children"은 한 단계 아래의 submodule까지만 표시하는 것이고
"modules"는 자신에게 속하는 모든 submodule들을 표시해주는 것이군요!

"named_modules", "named_children"은 module의 이름도 돌려주는데
그냥 module만 필요한 경우는 "modules", "children"를 사용하면 되겠네요!

아니 그런데 왜 "Function_D"가 "Function_C"를 참조하는 중이죠?
같은 기본 단위는 서로 독립적이어야 하는데 이러면 문제가 있을 것 같아요!
분석이 끝나면 수정을 해야겠어요!
```

### get_submodule

``` python
제가 만든 모델 내부에 어떤 module들이 있는지 잘 알겠어요!
이제 제가 원하는 특정 module만을 가져오고 싶어요!

Function_A를 가져다 줄 수 있을까요?
```

- [get_submodule - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=get_submodule#torch.nn.Module.get_submodule)


In [ ]:
# TODO : Function_A 를 가져오세요!
submodule = model.None


# 아래 코드는 수정하실 필요가 없습니다!
if submodule.__class__.__name__  == 'Function_A':
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("다시 도전해봐요!")

### Parameter

``` python
이제 module에 대한 자신감이 생겼어요!
그런데 문득 생각해보니까 Parameter에 대해서 공부하면서
제가 어떤 모듈에 Parameter를 생성해놨던 것 같아요!

저희가 module에서 module 목록을 보고 특정 module을
찾기도 했던 것처럼 Parameter에서도 똑같이 해봐요!
```

- [parameters - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=parameters#torch.nn.Module.parameters)
- [named_parameters - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=named#torch.nn.Module.named_parameters)
- [get_parameter - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=get#torch.nn.Module.get_parameter)


In [ ]:
# 4개의 Parameter를 만들었었군요!
for name, parameter in model.named_parameters():
    print(f"[ Name ] : {name}\n[ Parameter ]\n{parameter}")
    print("-" * 30)

[ Name ] : ab.b.W1
[ Parameter ]
Parameter containing:
tensor([10.], requires_grad=True)
------------------------------
[ Name ] : ab.b.W2
[ Parameter ]
Parameter containing:
tensor([2.], requires_grad=True)
------------------------------
[ Name ] : cd.d.W1
[ Parameter ]
Parameter containing:
tensor([3.], requires_grad=True)
------------------------------
[ Name ] : cd.d.W2
[ Parameter ]
Parameter containing:
tensor([5.], requires_grad=True)
------------------------------


``` python
아하! 제가 4개의 Parameter를 만들었었네요!
이름을 표시하니까 Parameter가 어디에 속하는지 알 수 있어 너무 좋아요!

- "Function_B"에 W1, W2 Parameter 2개
- "Function_D"에 W1, W2 Parameter 2개

"parameters"를 사용해서 목록을 확인해도 되지만
이름이 표시 안되니까 어떤 module에 속한
Parameter인지 알기가 너무 힘들 것 같아요!

Function_B에 속해있는 Parameter W1을 사용하고 싶은데
이를 가져다 주실수 있나요?
```

In [ ]:
# TODO : Function_B에 속하는 Parameter W1을 가져오세요!
parameter = model.None


parameter # 10

Parameter containing:
tensor([10.], requires_grad=True)

### Buffer

``` python
생각을 해보니까 buffer도 하나 추가해뒀던 것 같아요!
buffer도 같이 분석해봐요!
```

- [buffers - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=buffers#torch.nn.Module.buffers)
- [named_buffers - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=named_buffers#torch.nn.Module.named_buffers)
- [get_buffer - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=get_buffer#torch.nn.Module.get_buffer)


In [ ]:
# TODO : named_buffers를 사용해서 model에 속하는 buffer 전체 목록을 가져오세요!
for name, buffer in model.None:
    print(f"[ Name ] : {name}\n[ Buffer ] : {buffer}")
    print("-" * 30)

[ Name ] : cd.c.duck
[ Buffer ] : tensor([7.])
------------------------------
[ Name ] : cd.d.c.duck
[ Buffer ] : tensor([7.])
------------------------------


In [ ]:
# TODO : buffers를 사용해서 model에 속하는 buffer 전체 목록을 가져오세요!
for buffer in model.None:
    print(f"[ Buffer ] : {buffer}")
    print("-" * 30)

[ Buffer ] : tensor([7.])
------------------------------
[ Buffer ] : tensor([7.])
------------------------------


In [ ]:
# TODO : Function_C에 속하는 Buffer를 가져오세요!
buffer = model.None


buffer # 7

tensor([7.])

### 모델 수정하기 - Docstring 작성

``` python
가볍게 Docstring을 작성해봐요!
Numpy, Pydoc, Google 등 다양한 스타일이 있으니까 궁금하면
아래 링크에서 읽어보면서 공부해보도록 해요!

지금은 스타일 상관없이 Docstring이라는 것을 추가하기만 해보죠!
```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)

**✨ 유용한 자료 ✨**
- [Docstrings in Python - Data Camp](https://www.datacamp.com/community/tutorials/docstrings-python)

In [ ]:
import torch
from torch import nn
from torch.nn.parameter import Parameter

# TODO : Docstring을 추가해보세요!
class Model(nn.Module):
    """
    


    """
    def __init__(self):
        super().__init__()



# 아래 코드는 수정하실 필요가 없습니다!
model = Model()

if model.__doc__:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


### BatchNorm1d 분석해보기

``` python
PyTorch가 미리 만들어둔 module중 하나인 BatchNorm1d로 분석해봅시다!
```

- [Documentation main - PyTorch 공식 문서](https://pytorch.org/docs/stable/index.html)
- [torch.nn.BatchNorm1d - PyTorch 공식 문서](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm1d.html#torch.nn.BatchNorm1d)

In [ ]:
import torch
import torch.nn

module = nn.BatchNorm1d(10)

# TODO : nn.BatchNorm1d의 parameter와 buffer 갯수를 알아내세요!
parameter_n = len(list(module.None))
buffer_n = len(list(module.None))

# TODO : nn.BatchNorm1d의 buffer 이름을 알아내세요!
#        [이름, 이름, 이름] 형태로 저장해주세요!
buffer_names = [name for name, _ in module.named_buffers()]



# 아래 코드는 수정하실 필요가 없습니다!
answer = set(['running_mean', 'running_var', 'num_batches_tracked'])

if parameter_n == 2 and buffer_n == 3 and answer == set(buffer_names):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉
