In [1]:
import torch
import torch.nn.functional as F

In [2]:
tensor = torch.FloatTensor([0.5,0.7,0.1])
h_tensor = F.softmax(tensor, dim = 0) # softmax = 0~1 사이의 확률로 바꿔주는 함수, 합치면 1
h_tensor


tensor([0.3458, 0.4224, 0.2318])

In [3]:
h_tensor.sum()

tensor(1.0000)

In [8]:
y = torch.randint(5, (10,5)) # max = 5,  0~4, size = 10 x 5
y_label = y.argmax(dim=1) # input텐서 에 있는 모든 요소의 최대값 인덱스를 반환
y_label

tensor([0, 0, 2, 0, 3, 0, 0, 3, 1, 1])

In [9]:
F.one_hot(y_label)

tensor([[1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 0]])

In [6]:
import itertools
a = [1,2,3]
b = [4,5]
list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [7]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b) # 모든 경우의 수를 다 출력

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

## Torch autograd (자동 미분)

In [10]:
w = torch.tensor(2.0, requires_grad = True)
y = w ** 2
z= 10 * y + 50
z.backward()
w.grad

tensor(40.)

In [11]:
# Q = 3*a **3 - b ** 2 에 대한 자동미분
a = torch.tensor([2., 3.], requires_grad = True) # 연산을 위해서 미리 다 텐서 객체를 만들어줘야 한다.
b = torch.tensor([6., 4.], requires_grad = True) 
Q = 3*a **3 - b ** 2 
external_grad = torch.tensor([1., 1.])
Q.backward(gradient = external_grad) # Q 는 벡터(vector)이므로 Q.backward() 에 gradient 인자(argument)를 명시적으로 전달해야 합니다. 
# gradient 는 Q 와 같은 모양(shape)의 텐서로, Q 자기 자신에 대한 변화도(gradient)를 나타냅니다. 즉 dQ/dQ = 1

# backward 함수는 어떤 스칼라 값에 대한 출력 텐서의 변화도(gradient)를 전달받고, 동일한 스칼라 값에 대한 입력 텐서의 변화도를 계산합니다.
# 그러니까 gradient 를 구하고 싶다면 역전파를 시작할 지점에서 backward() 함수를 호출하란 말입니다.

a.grad

tensor([36., 81.])

In [ ]:
# Q를 a에 대해 미분하면 9a**2, b에 대해 미분하면 -2b
# a= [2, 3] 이므로 9* 2 *2 , 9*3*3 = 36, 81 이 되는 것 