In [14]:
## import
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score # Accuracy metrics 

In [33]:
# original data
data = pd.read_csv("/mnt/c/users/KOJUNSUNG/Downloads/x_train.csv")
target = pd.read_csv("/mnt/c/users/KOJUNSUNG/Downloads/y_train.csv")

# rebuild
data, target = data.drop(labels="Unnamed: 0",axis=1), target
dataset = pd.concat((data, target), axis=1)


In [34]:
data.shape

(2861, 132)

In [35]:
data.head()

x1        y1        z1        v1        x2        y2        z2  \
0  0.579180  0.494718 -1.260400  0.999884  0.598910  0.437344 -1.202794   
1  0.579247  0.492518 -1.121348  0.999892  0.599189  0.435712 -1.065062   
2  0.579256  0.492384 -1.103188  0.999899  0.599271  0.435453 -1.047567   
3  0.579180  0.491912 -1.137667  0.999905  0.599163  0.434376 -1.083351   
4  0.579315  0.492281 -1.154184  0.999911  0.599251  0.434340 -1.100381   

         v2        x3        y3  ...       z31           v31       x32  \
0  0.999647  0.615433  0.440355  ...  0.940863  5.854897e-07  0.738593   
1  0.999672  0.615862  0.438817  ...  1.082689  5.664001e-07  0.734784   
2  0.999691  0.616001  0.438468  ...  1.176795  5.734016e-07  0.732842   
3  0.999710  0.615937  0.436995  ...  1.153705  5.510733e-07  0.724409   
4  0.999729  0.616049  0.436875  ...  1.350937  5.601879e-07  0.725853   

        y32       z32       v32       x33       y33       z33       v33  
0  2.877994  0.449241  0.000004  0.548525  2.886744  0.250947  0.000006  
1  2.890085  0.500137  0.000004  0.547794  2.901754  0.407540  0.000006  
2  2.901172  0.495691  0.000004  0.547777  2.913632  0.506053  0.000006  
3  2.922381  0.584140  0.000004  0.535767  2.933913  0.466976  0.000005  
4  2.953179  0.608636  0.000004  0.538587  2.964739  0.654591  0.000005  

[5 rows x 132 columns]

In [36]:
dataset.head()

x1        y1        z1        v1        x2        y2        z2  \
0  0.579180  0.494718 -1.260400  0.999884  0.598910  0.437344 -1.202794   
1  0.579247  0.492518 -1.121348  0.999892  0.599189  0.435712 -1.065062   
2  0.579256  0.492384 -1.103188  0.999899  0.599271  0.435453 -1.047567   
3  0.579180  0.491912 -1.137667  0.999905  0.599163  0.434376 -1.083351   
4  0.579315  0.492281 -1.154184  0.999911  0.599251  0.434340 -1.100381   

         v2        x3        y3  ...           v31       x32       y32  \
0  0.999647  0.615433  0.440355  ...  5.854897e-07  0.738593  2.877994   
1  0.999672  0.615862  0.438817  ...  5.664001e-07  0.734784  2.890085   
2  0.999691  0.616001  0.438468  ...  5.734016e-07  0.732842  2.901172   
3  0.999710  0.615937  0.436995  ...  5.510733e-07  0.724409  2.922381   
4  0.999729  0.616049  0.436875  ...  5.601879e-07  0.725853  2.953179   

        z32       v32       x33       y33       z33       v33  Label  
0  0.449241  0.000004  0.548525  2.886744  0.250947  0.000006      1  
1  0.500137  0.000004  0.547794  2.901754  0.407540  0.000006      1  
2  0.495691  0.000004  0.547777  2.913632  0.506053  0.000006      1  
3  0.584140  0.000004  0.535767  2.933913  0.466976  0.000005      1  
4  0.608636  0.000004  0.538587  2.964739  0.654591  0.000005      1  

[5 rows x 133 columns]

In [37]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.1, shuffle=True, stratify=target, random_state= 1)

In [38]:
X_train.head()

x1        y1        z1        v1        x2        y2        z2  \
2158  0.262274  0.623575 -0.745098  0.999400  0.285123  0.550607 -0.766475   
667   0.608356  0.458854 -1.175270  0.999723  0.630769  0.398236 -1.115766   
2567  0.499951  0.630966 -1.407179  0.999730  0.530535  0.579422 -1.366270   
2187  0.139919  0.689523 -0.693515  0.995222  0.154531  0.605634 -0.760650   
1392  0.818627  0.557193 -1.547324  0.999716  0.865214  0.495062 -1.477190   

            v2        x3        y3  ...       z31       v31       x32  \
2158  0.998654  0.308800  0.545518  ...  1.007782  0.000013  0.579983   
667   0.999276  0.649712  0.399739  ...  0.378469  0.000032  0.720158   
2567  0.999422  0.547838  0.585423  ...  1.106318  0.000024  0.507962   
2187  0.991238  0.172302  0.589085  ...  0.943814  0.000004  0.581773   
1392  0.999153  0.884673  0.504148  ...  1.535036  0.000023  0.740311   

           y32       z32       v32       x33       y33       z33       v33  
2158  3.262597  0.111775  0.000064  0.377484  3.260891  0.349814  0.000047  
667   3.025121 -0.288044  0.000112  0.531430  3.024151 -0.367120  0.000141  
2567  3.050224 -0.154719  0.000042  0.349381  3.020129  0.360561  0.000040  
2187  3.368124 -0.033809  0.000013  0.365055  3.380414  0.278167  0.000012  
1392  3.296399  0.565340  0.000040  0.559390  3.272853  0.702644  0.000064  

[5 rows x 132 columns]

In [40]:
y_train.head() # 2= right, 1=middle , 0 =left

Label
2158      2
667       1
2567      2
2187      2
1392      0

In [39]:
print(X_train.shape, y_train.shape)

(2574, 132) (2574, 1)


In [41]:
Y_train = tf.keras.utils.to_categorical(y_train)# one hot encoding
Y_test = tf.keras.utils.to_categorical(y_test)

In [42]:
Y_train[4]

array([1., 0., 0.], dtype=float32)

In [43]:
Y_train.shape

(2574, 3)

In [44]:
# model 

# model 
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(128, activation='relu', input_shape=(132,)))
model.add(tf.keras.layers.Dropout(0.5)) # add dropout layer
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax')) # 1=forward, 2=right, 0=left
# for multiclassification, use softmax func.
# There is no CNN layer because there is no image input. 
# image input -> csv data -> modeling 

# Compile 

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [45]:
# Train the model
model.fit(X_train, Y_train, epochs=10)

Epoch 1/10
81/81 [==============================] - 1s 8ms/step - loss: 0.5454 - accuracy: 0.7918
Epoch 2/10
81/81 [==============================] - 0s 6ms/step - loss: 0.1731 - accuracy: 0.9553
Epoch 3/10
81/81 [==============================] - 0s 6ms/step - loss: 0.1094 - accuracy: 0.9685
Epoch 4/10
81/81 [==============================] - 0s 6ms/step - loss: 0.0657 - accuracy: 0.9817
Epoch 5/10
81/81 [==============================] - 0s 6ms/step - loss: 0.0523 - accuracy: 0.9856
Epoch 6/10
81/81 [==============================] - 1s 7ms/step - loss: 0.0425 - accuracy: 0.9868
Epoch 7/10
81/81 [==============================] - 1s 7ms/step - loss: 0.0389 - accuracy: 0.9899
Epoch 8/10
81/81 [==============================] - 1s 7ms/step - loss: 0.0364 - accuracy: 0.9907
Epoch 9/10
81/81 [==============================] - 1s 7ms/step - loss: 0.0338 - accuracy: 0.9899
Epoch 10/10
81/81 [==============================] - 1s 7ms/step - loss: 0.0247 - accuracy: 0.9934


In [46]:
# evaluate
results = model.evaluate(X_test, Y_test)
print('accuracy: ', results[1])

9/9 [==============================] - 0s 7ms/step - loss: 0.0091 - accuracy: 0.9965
accuracy:  0.996515691280365


In [47]:
model.save('Maded_model_2.h5') #save

In [50]:
model.predict(X_test)

9/9 [==============================] - 0s 2ms/step


array([[2.92698713e-03, 9.96869743e-01, 2.03364310e-04],
       [9.99999523e-01, 3.98854468e-07, 1.06289150e-07],
       [2.57149537e-07, 8.31968805e-07, 9.99998927e-01],
       [3.93663910e-08, 3.12759107e-06, 9.99996781e-01],
       [9.97825384e-01, 2.17326963e-03, 1.45946933e-06],
       [9.99986291e-01, 1.35604723e-05, 9.57966861e-08],
       [1.41939918e-10, 2.32622668e-08, 1.00000000e+00],
       [1.75367507e-08, 2.21266237e-06, 9.99997735e-01],
       [3.80597859e-10, 7.76623352e-08, 9.99999881e-01],
       [3.26360925e-03, 9.96495426e-01, 2.41022994e-04],
       [9.99966741e-01, 3.32190393e-05, 5.44894547e-08],
       [3.71250280e-06, 5.59849723e-04, 9.99436438e-01],
       [1.48413330e-03, 9.97292221e-01, 1.22360163e-03],
       [6.19589073e-08, 7.80035498e-06, 9.99992132e-01],
       [6.79387432e-03, 9.93005693e-01, 2.00429131e-04],
       [8.84518485e-08, 2.37302320e-05, 9.99976158e-01],
       [1.00000000e+00, 5.57731084e-10, 7.68426850e-11],
       [9.99999642e-01, 3.67631

In [48]:
!pwd

/mnt/c/Users/KOJUNSUNG/Desktop/lab/git/TIL/DL/Project


In [49]:
X_test.shape

(287, 132)

In [18]:
from tensorflow.keras.models import load_model

p_model=load_model('Maded_model.h5')
pred = p_model.predict(X_test)

9/9 [==============================] - 0s 2ms/step


In [20]:
pred[0]

array([9.990777e-01, 8.754170e-04, 4.696191e-05], dtype=float32)

In [29]:
# if you want to reverse one-hot encoding, use np.argmax()
pred[3].argmax()

1

In [30]:
results = []
for i in pred:
    results.append(i.argmax())
print(results)    

[0, 1, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 2, 0, 2, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 1, 1, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0, 1, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 0, 1, 0, 2, 0, 0, 2, 1, 2, 1, 2, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 1, 0, 2, 2, 1, 2, 2, 1, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 1, 1, 2, 2, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 2, 2, 0, 0, 2, 1]


In [33]:
round(np.mean(results))

1

In [34]:
map_dict = {0: "left", 1: "middle", 2: "right"}

In [36]:
pred_name = []
for i in results:
    pred_name.append(map_dict[i])
print(pred_name)

['middle', 'left', 'right', 'left', 'middle', 'left', 'left', 'middle', 'right', 'middle', 'middle', 'middle', 'right', 'middle', 'right', 'right', 'middle', 'middle', 'middle', 'left', 'left', 'left', 'middle', 'left', 'right', 'middle', 'right', 'middle', 'right', 'middle', 'middle', 'right', 'right', 'middle', 'middle', 'left', 'right', 'left', 'right', 'right', 'left', 'middle', 'right', 'right', 'right', 'right', 'right', 'right', 'middle', 'middle', 'middle', 'left', 'left', 'middle', 'left', 'right', 'left', 'right', 'right', 'middle', 'right', 'middle', 'middle', 'right', 'right', 'left', 'right', 'left', 'left', 'right', 'middle', 'left', 'left', 'right', 'right', 'middle', 'right', 'middle', 'right', 'right', 'middle', 'middle', 'left', 'left', 'left', 'middle', 'right', 'middle', 'left', 'middle', 'middle', 'left', 'right', 'right', 'left', 'middle', 'middle', 'right', 'middle', 'left', 'right', 'middle', 'left', 'middle', 'middle', 'left', 'right', 'middle', 'left', 'right'