In [1]:
## import
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score # Accuracy metrics 

2023-02-15 10:10:50.368538: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-15 10:10:52.113268: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/extras/CUPTI/lib64:/usr/local/cuda-11.2/lib64::/home/user/anaconda3/envs/tf/lib/
2023-02-15 10:10:52.115431: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/extras/

In [2]:
# original data
data = pd.read_csv("/mnt/c/users/KOJUNSUNG/Downloads/x_train.csv")
target = pd.read_csv("/mnt/c/users/KOJUNSUNG/Downloads/y_train.csv")

# # rebuild
# data, target = data.drop(labels="Unnamed: 0",axis=1), target.drop(labels="Unnamed: 0",axis=1)
# dataset = pd.concat((data, target), axis=1)


In [3]:
data.shape

(3000, 132)

In [5]:
data.head()

x1        y1        z1        v1        x2        y2        z2  \
0  0.628011  0.803910 -1.331938  0.998005  0.659864  0.731436 -1.286930   
1  0.628469  0.801049 -1.340854  0.998099  0.660312  0.725896 -1.292040   
2  0.630058  0.796810 -1.445468  0.998151  0.662527  0.719059 -1.394889   
3  0.631681  0.790357 -1.422371  0.998229  0.664590  0.713880 -1.369593   
4  0.633798  0.787396 -1.443058  0.998304  0.666405  0.710132 -1.387218   

         v2        x3        y3  ...       z31       v31       x32       y32  \
0  0.997851  0.680906  0.733898  ...  0.064412  0.018138  0.765906  3.471387   
1  0.997952  0.681232  0.726501  ...  0.134194  0.017520  0.827965  3.474091   
2  0.998014  0.683160  0.719084  ...  0.161804  0.016771  0.836411  3.472935   
3  0.998084  0.685157  0.714091  ...  0.218952  0.015809  0.833522  3.484890   
4  0.998158  0.686601  0.710050  ...  0.206674  0.014795  0.842069  3.482789   

        z32       v32       x33       y33       z33       v33  
0  0.127984  0.012243  0.560639  3.482920 -0.456769  0.015673  
1  0.050169  0.012537  0.621462  3.490263 -0.356971  0.015642  
2 -0.034858  0.012646  0.626235  3.492421 -0.337585  0.015287  
3 -0.010311  0.012439  0.624052  3.493925 -0.260463  0.014399  
4 -0.089077  0.012177  0.634687  3.487085 -0.280130  0.013524  

[5 rows x 132 columns]

In [36]:
dataset.head()

x1        y1        z1        v1        x2        y2        z2  \
0  0.579180  0.494718 -1.260400  0.999884  0.598910  0.437344 -1.202794   
1  0.579247  0.492518 -1.121348  0.999892  0.599189  0.435712 -1.065062   
2  0.579256  0.492384 -1.103188  0.999899  0.599271  0.435453 -1.047567   
3  0.579180  0.491912 -1.137667  0.999905  0.599163  0.434376 -1.083351   
4  0.579315  0.492281 -1.154184  0.999911  0.599251  0.434340 -1.100381   

         v2        x3        y3  ...           v31       x32       y32  \
0  0.999647  0.615433  0.440355  ...  5.854897e-07  0.738593  2.877994   
1  0.999672  0.615862  0.438817  ...  5.664001e-07  0.734784  2.890085   
2  0.999691  0.616001  0.438468  ...  5.734016e-07  0.732842  2.901172   
3  0.999710  0.615937  0.436995  ...  5.510733e-07  0.724409  2.922381   
4  0.999729  0.616049  0.436875  ...  5.601879e-07  0.725853  2.953179   

        z32       v32       x33       y33       z33       v33  Label  
0  0.449241  0.000004  0.548525  2.886744  0.250947  0.000006      1  
1  0.500137  0.000004  0.547794  2.901754  0.407540  0.000006      1  
2  0.495691  0.000004  0.547777  2.913632  0.506053  0.000006      1  
3  0.584140  0.000004  0.535767  2.933913  0.466976  0.000005      1  
4  0.608636  0.000004  0.538587  2.964739  0.654591  0.000005      1  

[5 rows x 133 columns]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.1, shuffle=True, stratify=target, random_state= 1)

In [7]:
X_train.head()

x1        y1        z1        v1        x2        y2        z2  \
1409  0.534103  0.489854 -1.321002  0.999090  0.557185  0.434099 -1.257694   
2017  0.330746  0.626786 -2.384874  0.999192  0.363776  0.553497 -2.335559   
1508  0.490392  0.483849 -1.273045  0.999244  0.511147  0.426281 -1.208298   
2488  0.159182  0.895470 -1.596916  0.996583  0.175321  0.814059 -1.629453   
1974  0.524813  0.482401 -1.435248  0.998926  0.549318  0.428488 -1.365214   

            v2        x3        y3  ...       z31       v31       x32  \
1409  0.998739  0.573937  0.433766  ...  0.381578  0.003851  0.663889   
2017  0.999062  0.385320  0.551774  ...  0.127520  0.005640  0.658133   
1508  0.998965  0.530705  0.424418  ...  0.358214  0.003645  0.676028   
2488  0.996558  0.192314  0.801144  ...  0.541357  0.029676  0.451155   
1974  0.998561  0.567435  0.427764  ...  0.459725  0.003777  0.663347   

           y32       z32       v32       x33       y33       z33       v33  
1409  3.121562  0.212650  0.006062  0.463877  3.115129 -0.057812  0.004562  
2017  3.040761  0.090834  0.005068  0.465035  3.100737 -0.361319  0.005257  
1508  3.129936  0.152201  0.006242  0.476956  3.100738 -0.088131  0.004476  
2488  3.003336  0.247043  0.015010  0.247103  3.090301  0.206825  0.033083  
1974  3.129468  0.189247  0.006504  0.466772  3.112898 -0.003536  0.004260  

[5 rows x 132 columns]

In [8]:
y_train.head() # 2= right, 1=middle , 0 =left

class
1409      1
2017      2
1508      1
2488      2
1974      1

In [5]:
print(X_train.shape, y_train.shape)

(2700, 132) (2700, 1)


In [6]:
Y_train = tf.keras.utils.to_categorical(y_train)# one hot encoding
Y_test = tf.keras.utils.to_categorical(y_test)

In [10]:
Y_train[4]

array([0., 1., 0.], dtype=float32)

In [11]:
Y_train.shape

(2700, 3)

In [7]:
# model 

# model 
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(128, activation='relu', input_shape=(132,)))
model.add(tf.keras.layers.Dropout(0.5)) # add dropout layer
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax')) # 1=forward, 2=right, 0=left
# for multiclassification, use softmax func.
# There is no CNN layer because there is no image input. 
# image input -> csv data -> modeling 

# Compile 

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


2023-02-15 10:11:26.207125: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-15 10:11:26.247993: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-15 10:11:26.248056: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-15 10:11:26.249652: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, 

In [8]:
# Train the model
model.fit(X_train, Y_train, epochs=10)

Epoch 1/10


2023-02-15 10:11:33.605109: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2023-02-15 10:11:33.633422: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x1cece470 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-02-15 10:11:33.633449: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 3080 Ti, Compute Capability 8.6
2023-02-15 10:11:33.654096: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-02-15 10:11:33.899883: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


85/85 [==============================] - 3s 8ms/step - loss: 0.5610 - accuracy: 0.7856
Epoch 2/10
85/85 [==============================] - 1s 7ms/step - loss: 0.0789 - accuracy: 0.9870
Epoch 3/10
85/85 [==============================] - 1s 6ms/step - loss: 0.0307 - accuracy: 0.9952
Epoch 4/10
85/85 [==============================] - 1s 6ms/step - loss: 0.0156 - accuracy: 0.9989
Epoch 5/10
85/85 [==============================] - 1s 6ms/step - loss: 0.0176 - accuracy: 0.9952
Epoch 6/10
85/85 [==============================] - 1s 7ms/step - loss: 0.0118 - accuracy: 0.9967
Epoch 7/10
85/85 [==============================] - 1s 6ms/step - loss: 0.0139 - accuracy: 0.9956
Epoch 8/10
85/85 [==============================] - 1s 6ms/step - loss: 0.0146 - accuracy: 0.9959
Epoch 9/10
85/85 [==============================] - 1s 6ms/step - loss: 0.0063 - accuracy: 0.9996
Epoch 10/10
85/85 [==============================] - 1s 7ms/step - loss: 0.0042 - accuracy: 0.9996


In [9]:
# evaluate
results = model.evaluate(X_test, Y_test)
print('accuracy: ', results[1])

10/10 [==============================] - 0s 6ms/step - loss: 9.1267e-04 - accuracy: 1.0000
accuracy:  1.0


In [10]:
model.save('Maded_model_4.h5') #save

In [16]:
model.predict(X_test)

19/19 [==============================] - 0s 3ms/step


array([[6.0585990e-09, 3.8889929e-08, 1.0000000e+00],
       [5.6523066e-09, 6.9247039e-07, 9.9999928e-01],
       [1.0889101e-02, 9.6603239e-01, 2.3078546e-02],
       ...,
       [2.8006685e-14, 1.0813359e-08, 1.0000000e+00],
       [1.2353816e-07, 2.0341283e-06, 9.9999785e-01],
       [1.6692317e-04, 9.9975604e-01, 7.6937235e-05]], dtype=float32)

In [16]:
!pwd

/bin/bash: /home/user/anaconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/mnt/c/Users/KOJUNSUNG/Desktop/lab/git/TIL/DL/Project


In [18]:
X_test.shape

(600, 132)

In [6]:
from tensorflow.keras.models import load_model

p_model=load_model('Maded_model.h5')
pred = p_model.predict(X_test)

10/10 [==============================] - 1s 3ms/step


2023-02-14 20:55:48.828644: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [7]:
pred[0]

array([9.9916601e-01, 3.0002990e-04, 5.3401606e-04], dtype=float32)

In [8]:
# if you want to reverse one-hot encoding, use np.argmax()
pred[0].argmax()

0

In [30]:
results = []
for i in pred:
    results.append(i.argmax())
print(results)    

[0, 1, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 2, 0, 2, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 1, 1, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0, 1, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 0, 1, 0, 2, 0, 0, 2, 1, 2, 1, 2, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 1, 0, 2, 2, 1, 2, 2, 1, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 1, 1, 2, 2, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 2, 2, 0, 0, 2, 1]


In [33]:
round(np.mean(results))

1

In [34]:
map_dict = {0: "left", 1: "middle", 2: "right"}

In [36]:
pred_name = []
for i in results:
    pred_name.append(map_dict[i])
print(pred_name)

['middle', 'left', 'right', 'left', 'middle', 'left', 'left', 'middle', 'right', 'middle', 'middle', 'middle', 'right', 'middle', 'right', 'right', 'middle', 'middle', 'middle', 'left', 'left', 'left', 'middle', 'left', 'right', 'middle', 'right', 'middle', 'right', 'middle', 'middle', 'right', 'right', 'middle', 'middle', 'left', 'right', 'left', 'right', 'right', 'left', 'middle', 'right', 'right', 'right', 'right', 'right', 'right', 'middle', 'middle', 'middle', 'left', 'left', 'middle', 'left', 'right', 'left', 'right', 'right', 'middle', 'right', 'middle', 'middle', 'right', 'right', 'left', 'right', 'left', 'left', 'right', 'middle', 'left', 'left', 'right', 'right', 'middle', 'right', 'middle', 'right', 'right', 'middle', 'middle', 'left', 'left', 'left', 'middle', 'right', 'middle', 'left', 'middle', 'middle', 'left', 'right', 'right', 'left', 'middle', 'middle', 'right', 'middle', 'left', 'right', 'middle', 'left', 'middle', 'middle', 'left', 'right', 'middle', 'left', 'right'