In [1]:
## import
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score # Accuracy metrics 

2023-02-08 17:08:01.523806: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-08 17:08:02.125477: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/extras/CUPTI/lib64:/usr/local/cuda-11.2/lib64::/home/user/anaconda3/envs/tf/lib/
2023-02-08 17:08:02.126993: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/extras/

In [2]:
# original data
data = pd.read_csv("/mnt/c/users/KOJUNSUNG/Downloads/x_train_1.csv")
target = pd.read_csv("/mnt/c/users/KOJUNSUNG/Downloads/y_train_1.csv")

# rebuild
data, target = data.drop(labels="Unnamed: 0",axis=1), target.drop(labels="Unnamed: 0",axis=1)
dataset = pd.concat((data, target), axis=1)


In [3]:
data.shape

(6000, 132)

In [4]:
data.head()

x1        y1        z1        v1        x2        y2        z2  \
0  0.781959  0.555121 -1.325833  0.999686  0.815969  0.509020 -1.268849   
1  0.780122  0.564212 -1.327176  0.999710  0.811703  0.516201 -1.268746   
2  0.777825  0.565557 -1.268318  0.999732  0.807802  0.517558 -1.206271   
3  0.775535  0.565395 -1.221586  0.999752  0.804169  0.517470 -1.158001   
4  0.773533  0.565905 -1.223320  0.999772  0.802300  0.518041 -1.157453   

         v2        x3        y3  ...       z31       v31       x32       y32  \
0  0.999067  0.832633  0.516675  ...  1.231486  0.000020  0.661514  2.869056   
1  0.999134  0.827644  0.525635  ...  1.348614  0.000019  0.695836  2.869520   
2  0.999199  0.823382  0.527669  ...  1.245925  0.000017  0.699483  2.873343   
3  0.999256  0.819652  0.527561  ...  1.044325  0.000016  0.702922  2.863769   
4  0.999315  0.817755  0.528336  ...  0.895194  0.000015  0.700703  2.866538   

        z32       v32       x33       y33       z33       v33  
0  0.262439  0.000028  0.499780  2.836488  0.594336  0.000051  
1  0.182526  0.000029  0.533526  2.842350  0.666288  0.000051  
2  0.192420  0.000027  0.530380  2.849359  0.571536  0.000047  
3  0.066147  0.000027  0.534221  2.842932  0.385441  0.000045  
4 -0.036576  0.000026  0.532314  2.846723  0.225016  0.000042  

[5 rows x 132 columns]

In [36]:
dataset.head()

x1        y1        z1        v1        x2        y2        z2  \
0  0.579180  0.494718 -1.260400  0.999884  0.598910  0.437344 -1.202794   
1  0.579247  0.492518 -1.121348  0.999892  0.599189  0.435712 -1.065062   
2  0.579256  0.492384 -1.103188  0.999899  0.599271  0.435453 -1.047567   
3  0.579180  0.491912 -1.137667  0.999905  0.599163  0.434376 -1.083351   
4  0.579315  0.492281 -1.154184  0.999911  0.599251  0.434340 -1.100381   

         v2        x3        y3  ...           v31       x32       y32  \
0  0.999647  0.615433  0.440355  ...  5.854897e-07  0.738593  2.877994   
1  0.999672  0.615862  0.438817  ...  5.664001e-07  0.734784  2.890085   
2  0.999691  0.616001  0.438468  ...  5.734016e-07  0.732842  2.901172   
3  0.999710  0.615937  0.436995  ...  5.510733e-07  0.724409  2.922381   
4  0.999729  0.616049  0.436875  ...  5.601879e-07  0.725853  2.953179   

        z32       v32       x33       y33       z33       v33  Label  
0  0.449241  0.000004  0.548525  2.886744  0.250947  0.000006      1  
1  0.500137  0.000004  0.547794  2.901754  0.407540  0.000006      1  
2  0.495691  0.000004  0.547777  2.913632  0.506053  0.000006      1  
3  0.584140  0.000004  0.535767  2.933913  0.466976  0.000005      1  
4  0.608636  0.000004  0.538587  2.964739  0.654591  0.000005      1  

[5 rows x 133 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.1, shuffle=True, stratify=target, random_state= 1)

In [6]:
X_train.head()

x1        y1        z1        v1        x2        y2        z2  \
3775  0.300066  0.849716 -2.010101  0.998459  0.324537  0.777605 -2.061031   
3496  0.304265  0.726899 -0.757936  0.998085  0.337590  0.659332 -0.787346   
3938  0.378057  0.685380 -1.890124  0.999011  0.411871  0.620648 -1.878775   
5123  0.514998  0.507714 -0.858561  0.999419  0.542675  0.449969 -0.820555   
5406  0.526033  0.525796 -0.845715  0.999154  0.549470  0.486763 -0.796662   

            v2        x3        y3  ...       z31       v31       x32  \
3775  0.996702  0.348969  0.770353  ...  0.703886  0.000017  0.533519   
3496  0.994813  0.358520  0.658444  ...  0.542620  0.000014  0.498279   
3938  0.997810  0.430972  0.623398  ...  0.769683  0.000008  0.452172   
5123  0.998405  0.560631  0.451783  ...  0.550872  0.000018  0.589064   
5406  0.997602  0.564331  0.487500  ...  0.180456  0.000035  0.645136   

           y32       z32       v32       x33       y33       z33       v33  
3775  3.030170 -0.263729  0.000030  0.363884  3.041019  0.041479  0.000060  
3496  2.983867 -0.314402  0.000034  0.328376  2.971227 -0.008512  0.000031  
3938  2.975990 -0.116937  0.000024  0.281366  2.957042  0.078533  0.000020  
5123  2.760756 -0.013625  0.000038  0.415611  2.751269 -0.016733  0.000031  
5406  2.669460 -0.354228  0.000072  0.488208  2.666490 -0.387921  0.000067  

[5 rows x 132 columns]

In [7]:
y_train.head() # 2= right, 1=middle , 0 =left

Label
3775      2
3496      2
3938      2
5123      1
5406      1

In [8]:
print(X_train.shape, y_train.shape)

(5400, 132) (5400, 1)


In [9]:
Y_train = tf.keras.utils.to_categorical(y_train)# one hot encoding
Y_test = tf.keras.utils.to_categorical(y_test)

In [10]:
Y_train[4]

array([0., 1., 0.], dtype=float32)

In [11]:
Y_train.shape

(5400, 3)

In [12]:
# model 

# model 
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(128, activation='relu', input_shape=(132,)))
model.add(tf.keras.layers.Dropout(0.5)) # add dropout layer
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax')) # 1=forward, 2=right, 0=left
# for multiclassification, use softmax func.
# There is no CNN layer because there is no image input. 
# image input -> csv data -> modeling 

# Compile 

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


2023-02-08 17:08:48.249691: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-08 17:08:48.253602: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-08 17:08:48.253648: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-08 17:08:48.254193: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, 

In [13]:
# Train the model
model.fit(X_train, Y_train, epochs=10)

Epoch 1/10


2023-02-08 17:08:55.378402: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2023-02-08 17:08:55.404090: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x7f2e9c016610 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-02-08 17:08:55.404121: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 3080 Ti, Compute Capability 8.6
2023-02-08 17:08:55.426564: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-02-08 17:08:55.671767: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


169/169 [==============================] - 3s 8ms/step - loss: 0.3686 - accuracy: 0.8702
Epoch 2/10
169/169 [==============================] - 1s 7ms/step - loss: 0.1032 - accuracy: 0.9726
Epoch 3/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0726 - accuracy: 0.9804
Epoch 4/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0604 - accuracy: 0.9830
Epoch 5/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0421 - accuracy: 0.9869
Epoch 6/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0424 - accuracy: 0.9861
Epoch 7/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0255 - accuracy: 0.9931
Epoch 8/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0242 - accuracy: 0.9931
Epoch 9/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0201 - accuracy: 0.9941
Epoch 10/10
169/169 [==============================] - 1s 7ms/step - loss: 0.0190 - accuracy: 0.9950


In [14]:
# evaluate
results = model.evaluate(X_test, Y_test)
print('accuracy: ', results[1])

19/19 [==============================] - 0s 11ms/step - loss: 0.0131 - accuracy: 0.9967
accuracy:  0.996666669845581


In [15]:
model.save('Maded_model_3.h5') #save

In [16]:
model.predict(X_test)

19/19 [==============================] - 0s 3ms/step


array([[6.0585990e-09, 3.8889929e-08, 1.0000000e+00],
       [5.6523066e-09, 6.9247039e-07, 9.9999928e-01],
       [1.0889101e-02, 9.6603239e-01, 2.3078546e-02],
       ...,
       [2.8006685e-14, 1.0813359e-08, 1.0000000e+00],
       [1.2353816e-07, 2.0341283e-06, 9.9999785e-01],
       [1.6692317e-04, 9.9975604e-01, 7.6937235e-05]], dtype=float32)

In [17]:
!pwd

/bin/bash: /home/user/anaconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/mnt/c/Users/KOJUNSUNG/Desktop/lab/git/TIL/DL/Project


In [18]:
X_test.shape

(600, 132)

In [18]:
from tensorflow.keras.models import load_model

p_model=load_model('Maded_model.h5')
pred = p_model.predict(X_test)

9/9 [==============================] - 0s 2ms/step


In [20]:
pred[0]

array([9.990777e-01, 8.754170e-04, 4.696191e-05], dtype=float32)

In [29]:
# if you want to reverse one-hot encoding, use np.argmax()
pred[3].argmax()

1

In [30]:
results = []
for i in pred:
    results.append(i.argmax())
print(results)    

[0, 1, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 2, 0, 2, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 1, 1, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0, 1, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 0, 1, 0, 2, 0, 0, 2, 1, 2, 1, 2, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 1, 0, 2, 2, 1, 2, 2, 1, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 1, 1, 2, 2, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 2, 2, 0, 0, 2, 1]


In [33]:
round(np.mean(results))

1

In [34]:
map_dict = {0: "left", 1: "middle", 2: "right"}

In [36]:
pred_name = []
for i in results:
    pred_name.append(map_dict[i])
print(pred_name)

['middle', 'left', 'right', 'left', 'middle', 'left', 'left', 'middle', 'right', 'middle', 'middle', 'middle', 'right', 'middle', 'right', 'right', 'middle', 'middle', 'middle', 'left', 'left', 'left', 'middle', 'left', 'right', 'middle', 'right', 'middle', 'right', 'middle', 'middle', 'right', 'right', 'middle', 'middle', 'left', 'right', 'left', 'right', 'right', 'left', 'middle', 'right', 'right', 'right', 'right', 'right', 'right', 'middle', 'middle', 'middle', 'left', 'left', 'middle', 'left', 'right', 'left', 'right', 'right', 'middle', 'right', 'middle', 'middle', 'right', 'right', 'left', 'right', 'left', 'left', 'right', 'middle', 'left', 'left', 'right', 'right', 'middle', 'right', 'middle', 'right', 'right', 'middle', 'middle', 'left', 'left', 'left', 'middle', 'right', 'middle', 'left', 'middle', 'middle', 'left', 'right', 'right', 'left', 'middle', 'middle', 'right', 'middle', 'left', 'right', 'middle', 'left', 'middle', 'middle', 'left', 'right', 'middle', 'left', 'right'